repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: node
      pass_filenames: false
      types: [python]
      additional_dependencies: ["pyright"]
      args: [--project, pyproject.toml]